apiVersion: v1
kind: Service
metadata:
  name: nodeport-service
spec:
  type: NodePort
  clusterIP: 10.43.100.100
  selector:
    app: helloworldweb
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30200